mex -largeArrayDims CRT_sum_mex.c
mex -largeArrayDims CRT_Multrnd_Matrix.c
mex -largeArrayDims CRT_sum_mex_matrix.c
mex -largeArrayDims DirMult_CRT_Matrix.c
mex -largeArrayDims DirMultTM_hGNBP.c
mex -largeArrayDims DCMLDA_GNBP_fully.c
mex -largeArrayDims Mult_Sparse.c
mex -largeArrayDims Multrnd_Matrix_mex_fast_v1.c
mex -largeArrayDims PFA_GNBP_partial.c
mex -largeArrayDims PFA_GNBP_fully.c
mex -largeArrayDims PFA_BNBP_collapsed.c